### ISSUE TITLE
Views and URLs maybe need to being to separated

### ISSUE THREAD

**Issue by muhamadzolfaghari** [RaufMasoumi/BookStore-app#1]
As I saw the source code, I noticed that your files such as views and URLs needs to be in the specific file by category or feature. For example, put the files related to authentication into auth views and URLs and routes as well. This work lets you have more control on that in case of maintenance and refactoring.

**Comment by RaufMasoumi** [comment]
Hi there, thank you for your attention! It was absolutely true and for this reason, I created three new apps such as Carts, Categories and Reviews and put the related codes into them :)
